image: php:5.6.20-cli

before_script:
  - php -v
  - which php
  - php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
  - php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '7228c001f88bee97506740ef0888240bd8a760b046ee16db8f4095c0d8d525f2367663f22a46b48d072c816e7fe19959') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - if find . -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi;
  - composer self-update
  - composer install --prefer-source --no-interaction
  - vendor/bin/phpcs -i

cache:
    paths:
        - vendor

test:
  script:
    - vendor/bin/phpunit --filter ItgalaxyCodingStandards vendor/squizlabs/php_codesniffer/tests/AllTests.php