image: php:5.6

before_script:
  - apt-get update -yq && apt-get install -y -qq git php5-xdebug
  - php5enmod xdebug
  - php -v
  - which php
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - mv composer.phar /usr/local/bin/composer
  - composer --version
  - composer self-update
  - composer install --prefer-source --no-interaction
  - vendor/bin/phpcs -i

cache:
    paths:
        - vendor

test:
  script:
    - composer test
