image: php:5.6.20-cli

before_script:
  - php -v
  - which php
  - if find . -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi;
  - composer self-update
  - composer install --prefer-source --no-interaction
  - vendor/bin/phpcs -i

cache:
    paths:
        - vendor

test:
  script:
    - vendor/bin/phpunit --filter ItgalaxyCodingStandards vendor/squizlabs/php_codesniffer/tests/AllTests.php