before_script:
  - bash ci/docker_install.sh > /dev/null
  - php -v
  - which php
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - mv composer.phar /usr/local/bin/composer
  - composer --version
  - composer self-update
  - composer install --prefer-source --no-interaction --no-suggest

cache:
    paths:
        - vendor

test:5.6:
    image: php:5.6
    script:
        - composer test

test:7.0:
    image: php:7.0
    script:
        - composer test

test:7.1:
    image: php:7.1
    script:
        - composer test
