sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - if find . -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi;
  - composer selfupdate
  - composer install

test:
  script:
    - composer test
