<?php
$string = "Hello There";
$string = "'Hello There'";
$string = "Hello $there";
$string = 'Hello'."$there '".'hi';
$string = "Hello"." There"."\n";
$string = 'Hello '.$there.' Greg';
$string = "<div class='$class'>";
$string = "Value: $var[test]";
$string = "Hello There\0";
$string = "Hello There\a";
$string = "Hello There\b";
$string = "Hello There\e";
$string = "Hello There\f";
$string = "Hello There\n";
$string = "Hello There\r";
$string = "Hello There\t";
$string = "Hello There\v";
$string = "Hello There\x13";
$string = "Hello There\'{$test}\'";
$string = "
Hello there";
$string = '
Hello there';
$string = "Hello
there";
$string = 'Hello
there';
$string = "
test
";
$string = "test{$var}";

$x = "bar = '$z',
baz = '" . $a . "'...$x";

echo "window.location = \"".$url."\";\n";
echo "";
