<?php
$test = [1];
$test = [1, 2];
$test = [1,];
$test = [
    1,
];
$test = [
    1,];
$test = ['foo' => 1, 'bar' => 2,];
$test = [
    'foo' => 1,
    'bar' => 2,
];
$test = ['foo' => 1, 'bar' => 2, ];
$test = [
    'foo' => 1,
    'bar' => 2
];
$test = [
    'foo' => 1,
    'bar' => 2
    ,
];
$test = ['foo' => 1, 'bar' => 2,/* test */];
$test = ['foo' => 1, 'bar' => 2, /* test */ ];
$test = [
    'foo' => 1,
    'bar' => 2,/* test */
];
$test = [
    'foo' => 1,
    'bar' => 2, /* test */
];
$test = [
    'foo' => 1,
    'bar' => 2,
    /* test */
];
