<?php
$test = array(1);
$test = array(1, 2);
$test = array(1,);
$test = array(
    1,
);
$test = array(
    1,);
$test = array('foo' => 1, 'bar' => 2,);
$test = array(
    'foo' => 1,
    'bar' => 2,
);
$test = array('foo' => 1, 'bar' => 2, );
$test = array(
    'foo' => 1,
    'bar' => 2
);
$test = array(
    'foo' => 1,
    'bar' => 2
    ,
);
$test = array('foo' => 1, 'bar' => 2,/* test */);
$test = array('foo' => 1, 'bar' => 2, /* test */ );
$test = array(
    'foo' => 1,
    'bar' => 2,/* test */
);
$test = array(
    'foo' => 1,
    'bar' => 2, /* test */
);
$test = array(
    'foo' => 1,
    'bar' => 2,
    /* test */
);
