<?php
$message = 'Bad code';
exit;
exit();
exit(1);
exit('Bad');
exit('Bad' . ' code');
exit($message);
exit(someFunction());
exit( );
exit(

);
exit(
);
?>
<?php exit ?>
<?php exit; ?>
<?php exit(); ?>
<?php exit(1); ?>
<?php exit('Bad'); ?>
<?php exit('Bad' . ' code'); ?>
<?php exit($message); ?>
<?php exit(someFunction()); ?>
<?php exit( ); ?>
<?php exit(

); ?>
<?php
exit(

);
?>
<?php exit(
); ?>
<?php
exit(
);
?>
<?php
die;
