<?php
global $variable;
global$variable;
global  $variable;
global
$variable;
global
    $variable;
global

    $variable;

global $variableFirst;
global $variableSecond;

global $test2;
// Comment
global $test;

global $test2;
// Comment
// Comment
global $test;

global $test2;
global $test2;
// Comment
// Comment
global $test;
global $test2;
?>
<?php global $variable; ?>
<?php
global $variable;
?>
<?php
if ($condition) {
    global $variable;
}

switch ($i) {
    case 0:
        global $variable;

        echo $variable;
        break;
    default:
        // Nothing
        break;
}

$variable = true;

// Comment
global $variable;

$variable = true;

// Comment
// Comment
global $variable;

$variable = true;

$variable = true;
// Comment
global $variable;

$variable = true;
// Comment
// Comment
global $variable;
?>
<?php global $variable; ?>
<?php
global $variable;
?>
<?php
switch ($i) {
    case 0:
        global $variable;
        break;
    default:
        // Nothing
        break;
}

switch ($i) {
    case 0:
        global $variable;
    default:
        // Nothing
        break;
}

if ($condition) {
    $variableFirst = true;

    global $variableSecond;
}

global $variable;
// Comment

$variable = true;

global $variable;
// Comment
// Comment

$variable = true;

global $variable;
// Comment
$variable = true;

global $variable;
// Comment
// Comment
$variable = true;

global $variable;
