<?php
include 'file.php';
include_once 'file.php';
require 'file.php';
require_once 'file.php';
?>
<?php include 'file.php'; ?>
<?php
include 'file.php';
?>
<?php
include 'file.php';
include_once 'file.php';

include 'file.php';
require_once 'file.php';

include 'file.php';
require 'file.php';

include 'file.php';
include 'file.php';

switch ($i) {
    case 0:
        include 'file.php';
        break;
    default:
        // Nothing
        break;
}

switch ($i) {
    case 0:
        include 'file.php';
    default:
        // Nothing
        break;
}

switch ($i) {
    case 0:

        include 'file.php';

        break;
    default:
        // Nothing
        break;
}

if ($condition) {
    include 'file.php';
}

if ($condition) {
    $variable = true;

    include 'file.php';
}

if ($condition) {
    $variable = true;
    include 'file.php';
}

if ($condition) {
    include 'file.php';
    $variable = true;
}

if ($condition) {

    include 'file.php';

}

// Comment
include 'file.php';

$variable = true;

// Comment
// Comment
include 'file.php';

$variable = true;

include 'file.php';
// Comment

$variable = true;

include 'file.php';
// Comment
// Comment

$variable = true;

$variable = true;
include 'file.php';

$variable = true;
// Comment
include 'file.php';

$variable = true;
// Comment
// Comment
include 'file.php';

include 'file.php';
$variable = true;

include 'file.php';
// Comment
$variable = true;

include 'file.php';
// Comment
// Comment
$variable = true;

include 'file.php';
