<?php
$a = 1;
$a =
    1;
$a
    =
    1;
$a

    = 1;
$a


    = 1;
$a
= 1;
$a
  = 1;

$condition = true;

if ($condition) {
    $a
        = 1;
}
?>
<?php $a = 1; ?>
<?php
$a = 1;
?>
<?php
$a
    = 1;
?>
<?php
$GLOBALS['TSFE']->additionalHeaderData[$this->strApplicationName]
    = $this->xajax->getJavascript(t3lib_extMgm::siteRelPath('nr_xajax'));

$var = 'string';

function getInstalledStandards(
    $includeGeneric = false,
    $standardsDir = ''
) {
}
