<?php
$integer = (int) ('string');
$integer = (int) 'string';
$integer=(int)'string';
$integer=(int)('string');
$integer=(int)('string')+(int)('string');
$integer = (int) ($array[0] + $array[0]) / 2;
$integer = (int) ($array[0] + $array[0]) + (int) ($array[0] + $array[0]);
$integer = (int) ( 'string' );
$integer = (int) (
    'string'
);
$integer = (int) (
    $array[0]
        + $array[0]
)
    + (int) (
        $array[0]
            + $array[0]
    );
