<?php

interface TemplateInterface
{
    public function setVariable($name, $var);
    public function getHtml($template);
}

interface InterfaceTemplate
{
    public function setVariable($name, $var);
    public function getHtml($template);
}

interface strangeInterface
{
    public function setVariable($name, $var);
    public function getHtml($template);
}

interface strange_Name
{
    public function setVariable($name, $var);
    public function getHtml($template);
}

interface StrangeName
{
    public function setVariable($name, $var);
    public function getHtml($template);
}

interface strange_NameInterface
{
    public function setVariable($name, $var);
    public function getHtml($template);
}

interface AInterface
{
    public function setVariable($name, $var);
    public function getHtml($template);
}
