<?php

trait HelloWorldTrait
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}

trait TraitHelloWorld
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}

trait StrangeName
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}

trait strangeTrait
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}

trait strange_Name
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}

trait strange_NameTrait
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}

trait ATrait
{
    public function sayHello()
    {
        echo 'Hello World!';
    }
}
