<?php ?>
<?php

?>
<?php echo 'test'; ?>
<?php
echo 'test';
?>
<?php  $test = 1;?>
<?php  $test = 1; ?>
<?php $test = 1;?>
<?php $test = 1;  ?>
<?php $test = 1;
?>
<?php
$test = 1; ?>
<?php
$test = 1;

?>
<?php

$test = 1;
?>
<?php
// Spaces before and after
?>
<?php // Spaces before and after ?>
<?php  // Spaces before and after ?>
<?php // Spaces before and after  ?>
<?php // Spaces before and after?>
<?php  // Spaces before and after  ?>
<?php
// Spaces before and after?>
<?php // Spaces before and after
?>
<?php
