<?php

class SimpleClassFirst
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}

class SimpleClassSecond
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}
$variable = true;

class SimpleClassThird
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}


$variable = true;
class SimpleClassFourth
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}

$variable = true;


class SimpleClassFifth
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}

$variable = true;

// Comment
class SimpleClassSixth
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}

// Comment

class SimpleClassSeventh
{
    public $var = 'default';

    public function displayVar()
    {
        echo $this->var;
    }
}
?><?php class Foo {}?><?php
